### ISSUE TITLE
Grid-like artifact detection is run on the 4x4 downsampled ssim map.

### ISSUE THREAD

**Issue by szabadka** [cloudinary/ssimulacra#1]
When the grid-like artifact detection is run for the first time, its input is not the full-sized ssim map of the image, as the comment on line 305 would suggest, but the 4x4 downsampled ssim map. The downsampling happens in line 293, in-place, for the purpose of computing the worst-ssim-block, and it is not changed after that.

Is this the expected behavior? If yes, perhaps there could be a comment explaining the reason behind it. Note that in the second iteration, the edgediff map is the same size as the full image.

**Comment by jonsneyers** [comment]
Good catch! This is indeed not the intended behavior, and we should get a better grid-like artifact detection if we fix this. Might need to recalibrate `worst_grid_weight` after this is fixed.
Thanks for noticing this!
