### ISSUE TITLE
Release raw dataset for perceptual metrics

### ISSUE THREAD

**Issue by jrmuizel** [cloudinary/ssimulacra#2]
The blob post announcing SSIMULACRA refers to a release of the dataset for comparing distortion metrics. It would be great if this could be released.

**Comment by idobarnoam** [comment]
Hi @jrmuizel,

We are planning to publish a post about lossy compressions benchmarks in the near future.
The dataset would be released when we publish that. 
The current timeframe for that publishing is the upcoming few months.

Hope this helps.
