### ISSUE TITLE
Is it intended to use edgediff instead of ssim_map when scale is 0?

### ISSUE THREAD

**Issue by future63** [cloudinary/ssimulacra#5]
if (scale == 0) {
   ...
   for(int twice=0; twice < 2; twice++) {
       if (twice) { ssim_map = edgediff; }
       ...
   }
}

// worst ssim in a particular 4x4 block (larger blocks are considered too because of multi-scale)
resize(ssim_map, ssim_map, Size(), 0.25, 0.25, INTER_AREA);

**Comment by jonsneyers** [comment]
You're right. This wasn't the intention.

**Comment by dng-dev** [comment]
Is there any suggestion how to fix this?
