### ISSUE TITLE
Windows build issue (cv.hpp)

### ISSUE THREAD

**Issue by Lee-lithium** [cloudinary/ssimulacra#9]
hello jonsneyers

my english is not good, sorry
[Windows 10 1803, mingw-w64, opencv 4.3]
I use cmd command >g++ ssimulacra.cpp -o ssimulacra.exe
and get this issue

ssimulacra.cpp:81:10: fatal error: cv.hpp: No such file or directory
 #include <cv.hpp>
          ^~~~~~~~
compilation terminated.

I don't know how to correct build cpp, I think i made a mistake...
and miss some path setting, 
I search tutorial, some tutorial use command, but some tutorial use Makefile,
Can you give me a hint? thank you for your help. :)

**Comment by tpiros** [comment]
See #6

**Comment by Lee-lithium** [comment]
> See #6 

Thank you very much @tpiros, @ jonsneyers.
I success build ssimulacra. :)
